/*
1) what is servlet and why use it?
=> Servlet is a technology, which is used to create dynamic web application.
   Servlet is an API that contains many interfaces and classes.
   Servlet technology is robust and scalable because of java.
   as we know that before Servlet we use CGI technology that means common gateway interfaces
   but we have question is why we need to use servlet instead of CGI .
   because of some disadvantage.
   1) suppose consider we have web application when suddenly no of client try to use that application
   it takes time to response.

   What is Advantages of servlet and why use it?
   1) Better performance :because it creates a thread for each request ,not process.
   2) Portability:because of uses java language.
   3) Robust: JVM manages servlets ,so we do not need to worry about the memory leak, garbage collection etc.
   4) Secure: because it uses java languages.

2) What is dynamic web pages and static web pages.
=> Static web pages:=> static pages are pre-generated and stored  as HTML files on the web servers.each
   time a user request a page ,the server sends the same pre-existing HTML file to the users browser.
   They are suitable for simple websites that do not require frequent content updates or user interactions.

   Dynamic web pages:=>Dynamic web pages are typically generated by server-side scripts or application that
   interact with database,external APIs,or other data sources, The resulting HTML is then sent to the users browser.
   Dynamic pages involve more complex development processes. They require server side scripting ,database integration,and
   potentially additional technologies like Javascript,AJAX or server-side frameworks.

3) What is server and client explain in details?
=> Server:=>
   Server is just like software or application.as we know that we can install no of software or application  in one machine
   also we can install no of server in one machine.
   Server is a computer or a system that provides services ro resources to other computers or devices.in the context of web development,
   a server refers to a computer or a networks of computers that host web applications ,websites ,or web services.

   Client:=>
   A client refers to a device or software application that accesses and interacts with the resources provided by a server. in the
   context of web development,the client typically refers to the web browser running  on a users device ,such as a computer ,
   smartphone, or tablet

   in summary ,the server is the computer or system that provides resources and services,hosting
   web applications or websites ,while the client is the device or software application,typically
   a web browser,that accesses and interacts with the content provided by server .The server handles the
   processing,storage ,and delivery of web content ,while the client renders and displays the content to the user,allowing
   them to interact with it.

4) What is protocol and explain type of protocol.
=> generally as we know that protocol refers to a set of rules. by using protocol we can communicate and interact with each other
   through the device or system.
   There are several type of protocol used in networking.
   1) TCP(Transmission Control Protocol)
   2) UDP(User Datagram P)
   3) IP(Internet Protocol)
   4) HTTP(Hypertext Transfer Protocol)
   5) FTP(File Transfer Protocol
   6) SMTP(Simple Mail Transfer Protocol)
   each protocol have different motive or uses.

5) Explain hierarchy of Servlet
=>



 */